
kind: pipeline
name: default
steps:
- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags
- name: test-init
  image: busybox
  commands:
  - chmod -R o+w /drone/src
- name: test
  image: node:12
  user: node  
  commands:
  - npm install
  - npm test
- name: docker 
  image: plugins/docker
  settings:
    repo: quay.io/natlibfi/melinda-record-import-controller
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
kind: secret
name: docker_username
data: +0udimkBLHwfXyRlRl8qYjGjNqiHnD0hFhUl8HKcU+f6lFxxrHeiQ9IP/i3rLFinmF0=
---
kind: secret
name: docker_password
data: QBn+0EQUlji0ZzcsJ6idFhZjlkMPEmm28gjpQcIj04xuUvoytXVKZV9rRp3pj+ZB5+DpZGn6XM5zXLgUerBAD+f68LQZL2noxstVhCUEd5JXF9mYFYK5kXL24yI=
