---
kind: pipeline
name: default
steps:

- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags

- name: audit
  image: node:14
  commands:
  - npm audit --package-lock-only --audit-level=moderate --production

- name: install
  image: node:14
  environment:
    NPM_CONFIG_IGNORE_SCRIPTS: true
  commands:
  - npm install -g npm@latest
  - npm ci

- name: test
  image: node:14
  commands:
  - npm test

- name: build
  image: node:14
  environment:
    NPM_CONFIG_IGNORE_SCRIPTS: true
  commands:
  - npm install -g npm@latest
  - npm run build
  - npm ci --production

- name: static-security-scan
  image: quay.io/natlibfi/njsscan
  commands:
    - njsscan dist

- name: docker
  image: plugins/docker
  settings:
    repo: quay.io/natlibfi/melinda-record-import-controller
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
kind: secret
name: docker_username
data: +0udimkBLHwfXyRlRl8qYjGjNqiHnD0hFhUl8HKcU+f6lFxxrHeiQ9IP/i3rLFinmF0=
---
kind: secret
name: docker_password
data: QBn+0EQUlji0ZzcsJ6idFhZjlkMPEmm28gjpQcIj04xuUvoytXVKZV9rRp3pj+ZB5+DpZGn6XM5zXLgUerBAD+f68LQZL2noxstVhCUEd5JXF9mYFYK5kXL24yI=
---
kind: signature
hmac: 610b2b92e5199eadbf4f22ad19c292c07c0a33082fdca1759fdcb8dfa8dfc66e

...
